downgrade node and plumber for now
because of error on checkout:
…
  Module node.behaviors.storage, line 31, in __setitem__
  Module node.utils, line 221, in wrapper
TypeError: can't apply this __setattr__ to persistent.Persistent object